Implementation of ES6 syntax modules
MarkoKermi/awesome_books_finished pull request #1
Opened 2023-01-16 15:48 UTC by MarkoKermi

- Re-creation of  Awesome books project using ES6 syntax. 
- Re-creation of clock/date part using library Luxon.

2023-01-16 17:52 UTC, PinkMoon25 requested changes
Hi @MarkoKermi , 

Good job so far! you have done really well :clap:
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/11F0d3IVhQbreE/giphy.gif"/>

## Highlights
linter checks :heavy_check_mark: 
github flow :heavy_check_mark: 
Add and remove functionality :heavy_check_mark: 
luxon :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

**- [ ] As mentioned in the project requirements we have to create the entry point for our JavaScript code called index.js or script.js if you prefer that, but the main thing is to have a single entry file and Import all your other js files which are suppose to be in the modules directory into this main entry file, Currently all your js file is in modules directory. can we try to fix this.**

**- [ ]  I noticed you have committed an empty js file clock.js, Please can we remove it as it is not the best practice to commit empty files to codebase, it can cause confusion :confused:** 

**- [ ] I see the code you have in your script.js is actually the displayBook code and it would be better if you name that displaybook file and your displayBoook file contains the structure of your book object i.e. your book class so you can rename it to just book.js. this will in turn make more sense and make the codebase follow best practices and ultimately will be more readable and easy to bugfix :bug:**  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 17:52 UTC, PinkMoon25 commented on modules/displayBook.js
> +  }
- [ ] good job refactoring :clap: , Please notice that one of the main goal of this project is to refactor it to use ES6 suntax, which uses arrow functions instead, I suggest we change all the functions to be arraw functions :pray: 
ex: 
```
const booksFilter = (eachBook) => {
    this.bookArray = this.bookArray.filter((book) => book !== eachBook);
  }
```

2023-01-16 17:52 UTC, PinkMoon25 commented on modules/script.js
> +}
- [ ] good job refactoring :clap: , Please notice that one of the main goals of this project is to refactor it to use ES6 syntax, which uses arrow functions instead, I suggest we change all the functions to be arrow functions :pray:

2023-01-16 17:52 UTC, PinkMoon25 commented on modules/script.js
> +  }
- [ ] good job refactoring :clap: , Please notice that one of the main goals of this project is to refactor it to use ES6 syntax, which uses arrow functions instead, I suggest we change all the functions to be arrow functions :pray:

2023-01-16 17:52 UTC, PinkMoon25 commented on modules/script.js
> +}
- [ ] good job refactoring :clap: , Please notice that one of the main goals of this project is to refactor it to use ES6 syntax, which uses arrow functions instead, I suggest we change all the functions to be arrow functions :pray:

2023-01-17 08:50 UTC, uwadonat approved these changes
## Hi @MarkoKermi,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- No linter errors ✔️
- Well organized project ✔️


![appr](https://user-images.githubusercontent.com/65860678/212819525-2cb1320f-c83a-444a-a33c-0b81625e0760.gif)
# Status: Approved ✔️✔️✔️
### Optional 
- Please for your next pull request remember to add a title. Also commit messages should be capitalized and in imperative form. 

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-17 08:52 UTC, merged